export const projects = [
  {
    title: 'AWS Covid Website',
    description: "Develop a API to Dynamodb and RDS, impliment Auto Mapper, CRUD, http get methods, and a client page. Also publish to AWS Elastic Beanstalk",
    image: '/images/1.png',
    tags: ['C#', 'ASP.NET', 'AWS'],
    source: 'https://github.com/fyaazbobat/AWS-Covid_Api',
    visit: 'https://github.com/fyaazbobat/AWS-Covid_Api',
    id: 0,
  },
  {
    title: 'LinkTree Clone',
    description:"Built a clone version of the popular site LinkTree. By adding a URL you can view all links by going to your LinkTree",
    image: '/images/2.png',
    tags: ['React', 'Nodejs'],
    source: 'https://github.com/fyaazbobat/LinkTreeClone',
    visit: 'https://fyaaz-linktree-react.herokuapp.com/',
    id: 1,
  },
  {
    title: 'C# Restaurant Bill Calculator',
    description: "This is a WPF app that calculates the bill at a restaurant.",
    image: '/images/3.png',
    tags: ['C#'],
    source: 'https://github.com/fyaazbobat/RestaurantBillCalculator',
    visit: 'https://github.com/fyaazbobat/RestaurantBillCalculator',
    id: 2,
  },
  {
    title: 'AWS RDS Movide CRUD',
    description: "Using ASP.NET created a movie website that is full CRUD. The site uses DynamoDB, S3 and Elastic Beanstalk.",
    image: '/images/4.png',
    tags: ['C#', 'ASP.NET', 'AWS'],
    source: 'https://github.com/fyaazbobat/fyaazLab3Movie',
    visit: 'https://github.com/fyaazbobat/fyaazLab3Movie',
    id: 3,
  },
  {
    title: 'Coupon Site (Skimlink API)',
    description: "This is a simple react website to fetech data from a api (Skimlink.com) to get coupons and display them.",
    image: '/images/5.png',
    tags: ['React', 'NodeJs', 'Heroku'],
    source: 'https://github.com/fyaazbobat/Coupon-Deals-Skimlink',
    visit: 'https://coupons-deals-frontend.herokuapp.com/',
    id: 4,
  },
  {
    title: 'Survey Site',
    description: "This website is for a group project that allows a user to sigh up and create/do a survey",
    image: '/images/6.png',
    tags: ['JavaScript', 'NodeJS', 'Heroku'],
    source: 'https://github.com/fyaazbobat/ArrowSurveys',
    visit: 'https://arrowsurvey.herokuapp.com/',
    id: 5,
  },
  {
    title: 'AWS GUI',
    description: "Use AWS IAM and DynamoDB to create a WPF app. The App creates a DynamoDB table to store the book and list them from user",
    image: '/images/7.png',
    tags: ['C#', 'AWS', 'DynamoDB'],
    source: 'https://github.com/fyaazbobat/fyaazLab2AWSGUI/tree/master',
    visit: 'https://github.com/fyaazbobat/fyaazLab2AWSGUI/tree/master',
    id: 6,
  },
  {
    title: 'Logistic Regression (Titanic DataSet)',
    description: "This is a inclass lab for Logistic Regression on the Titanic Dataset",
    image: '/images/8.png',
    tags: ['Python', 'Sklearn', 'Numpy'],
    source: 'https://github.com/fyaazbobat/DataLabTitanicLogisticRegression',
    visit: 'https://github.com/fyaazbobat/DataLabTitanicLogisticRegression',
    id: 7,
  },
];
